### ISSUE TITLE
فصل ۳ - حل روابط بازگشتی/بخش اول

### ISSUE THREAD

**Issue by saharzeinivand** [AliRazavi-edu/PNU_3983#1015]
https://github.com/AliRazavi-edu/PNU_3983/tree/master/AlgorithmsDesign/_Students/42_%D9%BE%D9%88%D8%B1%DB%8C%D8%A7%20%D8%B5%D9%81%D8%B1%DB%8C

**Comment by pooriasafari** [comment]
@saharzeinivand 
سلام انجام شد
لطفا بررسی بفرمایید

**Comment by pooriasafari** [comment]
@saharzeinivand

سلام فایل ویدویی با لینک جدید ارسال شد
لظفا بررسی بفرمایید
