### ISSUE TITLE
فصل ۸ - انشعاب و تحدید/بخش اول 

### ISSUE THREAD

**Issue by saharzeinivand** [AliRazavi-edu/PNU_3983#1027]

**Comment by fmohammadipour** [comment]
سلام
این بخش برعهده بنده هست

**Comment by fmohammadipour** [comment]
@saharzeinivand 
سلام
تمامی ویدئوهای مرتبط با بنده ادیت و به همراه تمامی منابع آپلود شدند و لینک دانلودشون در این مسیر قرار گرفت
https://github.com/AliRazavi-edu/PNU_3983/tree/master/AlgorithmsDesign/_Students/64_%D9%81%D8%B1%DB%8C%D8%A8%D8%A7%20%D9%85%D8%AD%D9%85%D8%AF%DB%8C%20%D9%BE%D9%88%D8%B1
لطفا این ایشو را ببندید
باتشکر
