### ISSUE TITLE
تکنیک عقب گرد فصل 7

### ISSUE THREAD

**Issue by ahjafari** [AliRazavi-edu/PNU_3983#1045]
https://aparat.com/v/QZz5J

**Comment by saharzeinivand** [comment]
سلام.برین داخل پوش استیودنت بعد اسم خودتون رو پیدا کنید و لینک فیلمتون رو اونجا قرار بدین

**Comment by ahjafari** [comment]
سلام این پیام از قبل مونده؟
چون انجام دادیم
