### ISSUE TITLE
سوالات زوج نوبت اول 95-94 و سوالات فرد نوبت اول 98- 97 نیما منصوری

### ISSUE THREAD

**Issue by nima212** [AliRazavi-edu/PNU_3983#1388]
[اول 98-97 سوالات فرد - پاسخ.docx](https://github.com/AliRazavi-edu/PNU_3983/files/5152599/98-97.-.docx)
[اول 95 - 94زوج - پاسخ.docx](https://github.com/AliRazavi-edu/PNU_3983/files/5152587/95.-.94.-.docx)

**Comment by saharzeinivand** [comment]
فایل هاتون رو باید در قسمت الگوریتم دیزاین بعد استیودنت بعد فولدری که به اسم شماست قرار بگیره

**Comment by nima212** [comment]
سلام
من سه روز پیش فایل ها رو آپلود کردم ولی چیزی نشون نمیده الان هم اجازه نمیده دو باره آپلود کنم

**Comment by saharzeinivand** [comment]
سلام در واتساپ یه من پیام بدین
