### ISSUE TITLE
پاسخ سوالات فرد و زوج امتحان

### ISSUE THREAD

**Issue by jamini68** [AliRazavi-edu/PNU_3983#1418]

**Comment by jamini68** [comment]
[algorithm exam.docx](https://github.com/AliRazavi-edu/PNU_3983/files/5177566/algorithm.exam.docx)
[algorithm exam.pdf](https://github.com/AliRazavi-edu/PNU_3983/files/5177567/algorithm.exam.pdf)

**Comment by jamini68** [comment]
[11_JA_BSc_IntroAlgo_CheckList_AR_3983.docx](https://github.com/AliRazavi-edu/PNU_3983/files/5177596/11_JA_BSc_IntroAlgo_CheckList_AR_3983.docx)
[JA_CV_CheckList_AR_3983 (1).docx](https://github.com/AliRazavi-edu/PNU_3983/files/5177597/JA_CV_CheckList_AR_3983.1.docx)

**Comment by saharzeinivand** [comment]
سلام.فایلهای پاسخ نامه شما باید در قسمت الگوریتم دیزاین بعد استیودنت بعد در ریف خودتون قرار بگیره .

**Comment by jamini68** [comment]
سلام
هر کاری می کنم قرار نمی گیره

**Comment by saharzeinivand** [comment]
در واتساپ به من پیام بدین لطفا
