### ISSUE TITLE
فهرست مطالب فایل Readme

### ISSUE THREAD

**Issue by alirazavi** [AliRazavi-edu/PNU_3983#2]
برای دسترسی به بخش های مختلف مطالب فایل ایجاد فهرست مطالب میتواند مفید باشد

**Comment by mrganji9** [comment]
بدین منظور که برای هر دایرکتوری یک فایل ریدمی ایجاد کنیم ؟ 
@alirazavi

**Comment by alirazavi** [comment]
نه فکر نکنم نیاز باشد
فایل ریدمی بزرگ شده فهرست مطالب با لینک درون فایلی مثل هشتک صفحه وب که ادرس میدهد به یک لیبل ئر.ن فایل کمک میکند که از فهرست بشود سریع رفت هر حایی که میخواهید
قاعدتا به ابتدای هر بحش
