### ISSUE TITLE
Fork and Pull request Tutorial

### ISSUE THREAD

**Issue by mohammadkad** [AliRazavi-edu/PNU_3983#23]
دوستانی که در فورک و پول مشکل دارند دقت کنند خیلی راحته

از داخل اکانت خودتون اول آدرس زیر رو فورک کنید 
https://github.com/AliRazavi-edu/PNU_3983

سپس به نسخه خودتون برید، دقت کنید که نسخه فورک شده خودتون باشه نه پروژه اصلی
میتونید زیرنویس های انگلیسی و فارسی هر ویدئویی که انتخاب میکنید رو ادیت کنید

سپس یه درخواست پول برای پروژه اصلی ارسال میکنید

البته استاد نظرشون اینه که شما کل پروژه رو کلون کنید و از طریق کامند این کارها رو بکنید اما برای شروع شاید اینجوری سریعتر روال کار براتون روشن بشه

اگر فرصت شد آموزش ویدئویی رو در آپارات میذارم

ممنون.

**Comment by mrganji9** [comment]
سلام .
خیلی ممنون آقای کدخدایی و همچنین دقت کنید که در لینک زیر حتما مجموعه فیلمهایی که دارید روی اونها کار میکنید رو انتخاب کنید
https://github.com/AliRazavi-edu/PNU_3983/projects/2

**Comment by mohammadkad** [comment]
با سلام

مشخص شد اگر مشکلی داشت اعلام بفرمائید تا تصحیح کنم

در فاز اول زیرنویس انگلیسی 5 قسمت اول مجموعه آموزش ترکیب متدهای مدیریت پروژه رو انتخاب کردم
Linkedin Blending Project Management Methods

**Comment by fmohammadipour** [comment]
با سلام
ویدئو آموزشی ضبط شده توسط بنده درباره همین موضوع را از آدرس زیر می توانید دریافت کنید
http://dl1.abrim.ir/Videos/FMP/GIT2.np4

**Comment by SAMashiyane** [comment]
با سلام خدمت دوستان اگر دوستان تمایل به استفاده از خط فرمان ویا لینوکس جهت انجام پروژه ودرخواست پول رکوییست هستند می توانند از ویدیو های زیر در اپارات که توسط اینجانب تهیه شده استفاده کنند امیدوارم مفیدباشد
قسمت اول اشنایی مقدماتی
https://www.aparat.com/v/a2kuF
قسمت دوم ایجاد شاخه وفرستادن پول رکویست
https://www.aparat.com/v/mQ1IS
