### ISSUE TITLE
تهیه زیر نویس برای بیست قسمت مبانی مدیریت پروژه نرم افزار

### ISSUE THREAD

**Issue by rasoolmoniri** [AliRazavi-edu/PNU_3983#24]
به نام خدا
با عرض سلام
اینجانب رسول منیری به شماره دانشجویی980000665 هستم
که بیست قسمت مبانی مدیریت پروژه نرم افزار را برای ترجمه فارسی انتخاب کرده ام

**Comment by alirazavi** [comment]
سلام
برای اینکه تداخل ایجاد نشود لینک فیلی که میخواهید روی آن کار کنید را حتما در مورد ایجاد شده بگذارید 
در ضمن برای هر فایل یک مورد کاری ایجاد کنید
یکدفعه حجم بزرگی را برداشتن جلو کار دیگران را میگیرد و با اصول کانبان و اجایل مغایر است
