### ISSUE TITLE
اصلاح اسامی پوشه ها

### ISSUE THREAD

**Issue by alirazavi** [AliRazavi-edu/PNU_3983#3]
سلام
اسم پوشه ها اگر با شماره باشد هم اولویت و اهمیت و ترتیب مطالعه را نشان میدهد و هم ارجاع به آنها ساده تر میشود

اگر مشکل فنی وجود ندارد بنظر اسم ها اصلاح شوند بهتر باشد

_Originally posted by @alirazavi in https://github.com/AliRazavi-edu/PNU_3983/issues/1#issuecomment-670422380_

**Comment by mrganji9** [comment]
سلام .
 مشکلی وجود ندارد و اسامی پوشه ها آپدیت می شود
