### ISSUE TITLE
انتخاب موضوع (تهیه زیر نویس برای همکاری تحلیلگر کسب و کار با مدیر پروژه - قسمت ۱۲)

### ISSUE THREAD

**Issue by mrganji9** [AliRazavi-edu/PNU_3983#34]
سلام .
 
تهیه زیر نویس فارسی و انگلیسی این بخش (قسمت ۱۲) رو بنده به عهده میگیرم.

لینک فایل ها زیر نویسی که من کار خواهم کرد : 
https://github.com/AliRazavi-edu/PNU_3983/tree/master/SoftwareProjectManagement/_12_linkedin-business-analyst-and-project-manager-collaboration

لینک دانلود ویدئوها :
https://git.ir/linkedin-business-analyst-and-project-manager-collaboration

**Comment by taherimasoomeh475** [comment]
انتخاب قسمت اول تا سوم پروژه پایتون
