### ISSUE TITLE
انتخاب فصل مورد نظر برای ارائه(دانشجویان ارشد درس الگوریتم جبرانی)

### ISSUE THREAD

**Issue by saharzeinivand** [AliRazavi-edu/PNU_3983#38]
سلام.دانشجویان میتونن  فصل مورد نظرشون رو انتخاب کنن برای ارائه(هر دو نفر یک فصل).لطفا قبل از انتخاب فصل نگاه کنید ببینید دانشجویان دیگر چه فصلی رو انتخاب کردن که یوقت فصل تکراری انتخاب نکنید.با تشکر

**Comment by alirazavi** [comment]
این را چه کسی دارد انجام میدهد؟

بعبارتی این اطلاعیه است نه مورد کاری!

**Comment by saharzeinivand** [comment]
استاداطلاعیه زدم که بعدش هرکسی بیاد بگه کدوم فصل رو انتخاب کرده.یعنی این پیغام رو حذف کنم ؟
