### ISSUE TITLE
استحراج متن صوت ویدیو ها

### ISSUE THREAD

**Issue by alirazavi** [AliRazavi-edu/PNU_3983#4]
نرم افزار ساده زیر میتواند مورد استفاده واقع شود

https://github.com/raryelcostasouza/pyTranscriber/releases/download/v1.4-stable/pyTranscriber-v1.4-windows-portable.zip

**Comment by mohammadkad** [comment]
سلام

من داشتم یه برنامه با پایتون توسعه میدادم اما توی این فرصت کم بهتره از نرم افزاری که شما معرفی کردید استفاده کنیم 

سپاسگزارم

**Comment by mrspouya** [comment]
سپاسگزارم

**Comment by alirazavi** [comment]
سلام
مشکلی نیست میتوانید آن کار را ادامه دهید چون من دیدم برنامه را خیلی خوب کار میکند اما ی=قینا مشکلاتی با زبان فارسی دارد و میشود هم روی رابط کاربریش بیشتر کار کرد و هم روی آپشن هایش

برای آینده فرصت داشتید حتما ادامه میدهیم در فالب یک پروژه جداگانه

در ضمن من نسخه پورتابل را گذاشتم چون موقت است بچه ها نسازی به نصب نداشته باشند و کامپیوترشان شلوغ نشود

نصب هم بکنند عالی است و مشکلی ندارد
