### ISSUE TITLE
پروژه الگوریتم پیشرفته /الگوریتم ادموندز-کارپ /سحررجبی

### ISSUE THREAD

**Issue by Saharrajabi** [AliRazavi-edu/PNU_3983#41]
با سلام
بنده در حال کدنویسی وشبیه سازی الگوریتم ادموندز کارپ فصل 26 کتاب درسی به زبان جاوا اسکریپت هستم

**Comment by mrganji9** [comment]
خانوم رجبی سلام .
نیاز به اساین کردن استاد و دیگران نیست .
تسک مربوط به شما ایجاد شد

**Comment by alirazavi** [comment]
سلام خانم زینی وند
چرا بسمت عقب از این پروکرس اوردید توی تو دو؟
