### ISSUE TITLE
06 - en - 003

### ISSUE THREAD

**Issue by alirazavi** [AliRazavi-edu/PNU_3983#45]
https://github.com/AliRazavi-edu/PNU_3983/blob/master/SoftwareProjectManagement/_06_linkedin-blending-project-management-methods/en/003-Waterfall%20project%20life%20cycle-git.ir.en.srt

**Comment by shfathollahi** [comment]
@mrganji9 man mikham ino anjam bedam

**Comment by shfathollahi** [comment]
@mrganji9 anjam shod
