### ISSUE TITLE
انتخاب موضوع( زیرنویس فارسی برای قسمت ۱ تا ۱۹ فصل ۱۲)

### ISSUE THREAD

**Issue by mrspouya** [AliRazavi-edu/PNU_3983#567]
سلام وقت بخیر
  افسانه پویا تولید زیرنویس فارسی برای قسمت ۱ تا ۱۹ فصل ۱۲.

**Comment by mrganji9** [comment]
سلام .
انتخاب این قسمت برای شما مقدور نیست . اقای منیری قبلا انتخاب کرده اند و لطفا دقت کنید
