### ISSUE TITLE
11 - en - 060 انتخاب فایل 

### ISSUE THREAD

**Issue by hamidghaffarii** [AliRazavi-edu/PNU_3983#568]
@mrganji9 

سلام لطفا این قسمت برای بنده رزرو کنید درصورت امکان پذیر نبودن لطفا یک قسمت زیرنویس انگلیسی به اتخاب خودتون رزرو کنید. سپاس

**Comment by mrganji9** [comment]
سلام . انتخاب ها و تشخیص اینکه کدام زیرنویس رو انجام میدید همگی برعهده شماست . لطفا یک سری ۲۰ تایی برای شروع مشخص کنید.
