### ISSUE TITLE
تهیه زیرنویس انگلیسی ویدئو شمار ۱ تا ۳۰ فایل شماره 11

### ISSUE THREAD

**Issue by alialiakkbaridehkordi** [AliRazavi-edu/PNU_3983#571]
اینجانب در حال تهیه زیر نویس  انگلیسی  ویدئو  1تا 20 فایل  11
_linkedin-project-management-foundations با عنوان 
می باشم

**Comment by alialiakkbaridehkordi** [comment]
@mrganji9  سلام من تهیه زیر نویس انگلیسی این فایل را انجام میدم

**Comment by mrganji9** [comment]
به درخواست شما ۱۰ فایل اضافه شد.
