### ISSUE TITLE
انتخاب ترجمه تحلیل کسب وکار

### ISSUE THREAD

**Issue by mrspouya** [AliRazavi-edu/PNU_3983#573]
سلام وقت بخیر
افسانه پویا دوره تحلیل کسب وکارقسمت دوره تفکر انتقادی را ازفایل 1 تا 22 ترجمه میکنم
https://www.linkedin.com/learning/critical-thinking/welcome-to-critical-thinking?autoplay=true&trk=course_preview&upsellOrderOrigin=default_guest_learning

**Comment by mrganji9** [comment]
سلام . خانم پویا باید به روشی که در ویدئوها گفته شده عمل کنید

**Comment by mrganji9** [comment]
برای ویدیو هایی که خودتون جدا از مباحث گفته شده زیر نویس تهیه کردید با استاد صحبت کنید
