### ISSUE TITLE
انتخاب موضوع(قسمت چهارم  آموزش گردش کارتولید کارآمد برای پایتون)

### ISSUE THREAD

**Issue by AlirezaNazariii** [AliRazavi-edu/PNU_3983#581]
من 20 فایل اول این فصل را ترجمه میکنم

**Comment by fazele-kimiaee** [comment]
https://github.com/AlirezaNazariii/PNU_3983/tree/master/SoftwareProjectManagement/_04_linkedin-efficient-python-production-workflows/en
