### ISSUE TITLE
006-Constraint management-git.ir

### ISSUE THREAD

**Issue by shfathollahi** [AliRazavi-edu/PNU_3983#592]
می خوام برای این فایل زیر نویس انگلیسی بزارم

**Comment by mrganji9** [comment]
@shfathollahi نیازی به ایجاد این ایشو نیست و 
برای همه فایل ها ایشو ایجاد شده و 
به این قسمت توجه کنید :‌
https://github.com/AliRazavi-edu/PNU_3983/projects/2

**Comment by mrganji9** [comment]
@shfathollahi بگردید و زیر ایشوی مربوط به فایلتون که ایجاد شده کامنت بذارید
