### ISSUE TITLE
ایجاد زیر نویس فارسی برای فصل بیستم از بخش 08 تا بخش 12

### ISSUE THREAD

**Issue by pooriasafari** [AliRazavi-edu/PNU_3983#636]
@mrganji9 سلام این بخش رو من انجام میدم

**Comment by fmohammadipour** [comment]
سلام این بخش در حال انجام هست توسط من. توی issue ها ببینید به بنده اساین شده

**Comment by mrganji9** [comment]
@pooriasafari اقای صفری با هماهنگی کی این فایل رو انتخاب کردید ؟ مگر فصل شما مشخص نشده ؟
