### ISSUE TITLE
انتخاب موضوع(فصل۹ - تولید زیرنویس فارسی و انگلیسی)

### ISSUE THREAD

**Issue by pooriasafari** [AliRazavi-edu/PNU_3983#639]
@mrganji9 
@AliRazavi-edu/software-project-management-team 
ایجاد زیر نویس انگلیسی و فارسی برای فصل 9
پوریا صفری
مدیریت پروژه نرم افزاری

**Comment by pooriasafari** [comment]
@mrganji9 
آقای گنجی عزیر اگه امکانش هست خودتون یه قسمت از کار رو که هنوز کسی روش کار نکرده رو برای من انتخاب کنید اگه حجمش زیاد باشه اصلا ایرادی نداره
قسمت ترجمه زیر نویس های فارسی باشه لطفا

**Comment by pooriasafari** [comment]
@mrganji9 
سلام وقت بخیر
برای کل بخش 9 زیر نویس انگلیسی ایجاد شد 
لطفا بررسی بفرمایید

**Comment by mrganji9** [comment]
@pooriasafari کلا یک فایل فرستادی آقای صفری . بقیه رو هم باید ارسال کنید

**Comment by pooriasafari** [comment]
@mrganji9 

یه برنچ به اسم خودم ایجاد کردم و با این دستور براتون ارسال کردم

git add .

git commit -m "add full 09 - en Subtitle "


git push -u https://github.com/pooriasafari/PNU_3983.git PooriaSafari

**Comment by pooriasafari** [comment]
@mrganji9 

اگه ویدئویی باقی مونده که هنوز زیر نویس انگلیسی نداره برای من تعریف کنید که براش زیر نویس انگلیسی ایجاد کنم
ممنونم

**Comment by mrganji9** [comment]
@pooriasafari  مهندس دقت کن فایلایی که فرستادی مشکل داشت. فایل فارسی برای زیرنویس انگلیسی فرستادی

**Comment by pooriasafari** [comment]
@mrganji9 
همش مشکل داشت ؟

**Comment by pooriasafari** [comment]
@mrganji9 
لطفا مجدد بررسی کنید 
من الان توی پروژه اصلی هم نگاه کردم فایل های من اومده توی فصل 9

**Comment by pooriasafari** [comment]
@mrganji9 
سلام آقای مهندس عزیز
فایل زیر نویس فارسی هم براتون ارسال کردم
انجام شد.
