### ISSUE TITLE
فصل هشتم کتاب : انشعاب و تحدیدطراحی الگوریتم(جبرانی) سحررجبی 980199424

### ISSUE THREAD

**Issue by Saharrajabi** [AliRazavi-edu/PNU_3983#695]
با سلام 
من و خانم فریبا محمدی پور در حال اماده سازی ارائه فصل هشتم کتاب : انشعاب و تحدید هستیم

**Comment by fmohammadipour** [comment]
@mrganji9 @saharzeinivand 
وقت بخیر ممنون میشم این رو به من هم assign کنید
و in progress بشه داخل لینک زیر
https://github.com/AliRazavi-edu/PNU_3983/projects/4

**Comment by fmohammadipour** [comment]
+
