### ISSUE TITLE
تقسیم کردن درصدی از ویدئوها بین دانشجویان

### ISSUE THREAD

**Issue by mrganji9** [AliRazavi-edu/PNU_3983#7]
سلام.
برای عدم ایجاد به هم ریختگی و ناهماهنگی پیشنهاد میکنم دوستان یکی از دوره ها را انتخاب کنند و در لیست کانبان کارت مربوطه را اضافه کنیم
برای دانشجویان فعال تر هم مقداری از این ترجمه ها باقی می ماند و میتوانند مجدد انتخاب کنند و فعالیت بیشتر خود را نشان دهند

@alirazavi

**Comment by saharzeinivand** [comment]
سلام.پیشنهاد خوبیه.

**Comment by alirazavi** [comment]
> سلام.
> برای عدم ایجاد به هم ریختگی و ناهماهنگی پیشنهاد میکنم دوستان یکی از دوره ها را انتخاب کنند و در لیست کانبان کارت مربوطه را اضافه کنیم
> برای دانشجویان فعال تر هم مقداری از این ترجمه ها باقی می ماند و میتوانند مجدد انتخاب کنند و فعالیت بیشتر خود را نشان دهند
> 
> @alirazavi

صدور و درخواست انجام کار باید مشخص وبدون ابهام باشد
همکاران دانشجوی عضو پروژه مختار هستند در انتخاب درخواست ها و کارهای انها بصورت خودکار رصد میشود و ارزیابی بر اساس همین فعالیت ها صورت خواهد گرفت لذا همه ازاد هستند که کاری را انجام دهند یا ندهند

آنچه مهم است صدور درخواست انجام کار هم میتواند توسط دانشحویان انجام شود

برای اینکار لازم است برای تک تک ویدیوها صدور درخواست کار شود

کارها بایستی بر اساس اولویت و وابستگی ها انجام شود

مثلا ترجمه قبل از ایجاد فایل زیر نویس امکان پذیر نیست

آموزش دانشجویان نیز با متنانت و یکی یکی باید صورت پذیرد تا حجم زیاد مراجعات موجب بهم خوردن کارها در مخزن پروژه نشود

**Comment by SAMashiyane** [comment]
#7با سلام وعرض خسته نباشید خدمت استاد ودوستان عزیز با توجه به فرمایش استاد مبنی بر انتخاب موضوعات انتخابی اینجانب در حال ترجمه زیرنویس فصل هشتم(مدیریت پروژه های پایتون می باشم
دوستان در هنگام انتخاب جهت جلوگیری از تداخل   این موضوع را درنظر داشته باشند
 conflict  اجتناب از
