### ISSUE TITLE
انتخاب موضوع :فصل 20 فایل 34 تا 54

### ISSUE THREAD

**Issue by BehnazRafiei** [AliRazavi-edu/PNU_3983#730]
تهیه زیرنویس فارسی

**Comment by mrganji9** [comment]
@fmohammadipour خانم محمدی پوی ایشون با شما هم گروه هستند . ۲۰ فایل آخر رو ترجمه میکنند . در مورد ۱۴ فایل باقی مانده میتوانید با هم به توافق برسید
@BehnazRafiei

**Comment by BehnazRafiei** [comment]
خانم محمدی پور چطور می توانم فایلها را به خودم مجدد assign  کنم ؟
اشتباه assignment را پاک کردم .
@fmohammadipour

**Comment by BehnazRafiei** [comment]
ترجمه فایلهای زیرنویس

**Comment by BehnazRafiei** [comment]
جناب گنجی ظاهرا ایشو مربوط به من را زحمت کشیدین اساین کردین ، ولی چون سر کلاس اشاره کردین که هنوز اساین نشده ،کامنت گذاشتم. 

mrganji9@

**Comment by mrganji9** [comment]
@BehnazRafiei خانم رفیعی منظورم تک تک فایل های مربوط به شما در قسمت زیرنویسهای فارسی بود
