### ISSUE TITLE
ایجاد راهنمای سوالات پرشمار -  FAQ

### ISSUE THREAD

**Issue by alirazavi** [AliRazavi-edu/PNU_3983#9]
کثرت سوالات مشابه در کارهای جمعی نیازمند ایجاد پاسخ نامه مدون و ساخت یافته ایست که میتواند به بسیاری از سوالات پاسخگو بوده باشد و فرصت مدیران پروژه را بجای پاسخگویی تکراری به سوالات مشابه به پردازش ایده های جدید آزاد نماید

**لذا لازم است یکی از عزیزان دانشجو عهده دار این مهم گردد تا سوالات دیگر عزیزان بی پاسخ نمانند**

**Comment by SAMashiyane** [comment]
با سلام خدمت دوستان من در این قسمت میتوانم در حد توان جهت پاسخ به سوالات در خدمت دوستان باشم

**Comment by fmohammadipour** [comment]
با سلام بنده نیز دل حد توان اعلام آمادگی میکنم

**Comment by shfathollahi** [comment]
@fmohammadipour ببخشید خانم محمدی پور در مدیریت کانال یوتیوب اصطلاح  interlaced videoدیدیم ظاهرا معنیش میشه فیلم در هم تنیده ولی جالب نیست این معنی.با توجه به اینکه حوزه کار ترجمه شما در مورد کانال یوتیوب بود گفتم از شما مشورت بگیرم
